config/routes.rb
Rails.application.routes.draw do
  devise_for :learners

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  resources :learners, only: [:index, :show, :edit, :update] do
    get '/following' => 'relationships#following', as: 'following'
    get '/follower' => 'relationships#follower', as: 'follower'
  end

  resources :posts do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
  delete '/notifications/destroy_all' => 'notifications#destroy_all', as: 'destroy_all'


  get '/questions' => 'posts#question', as: "question"
  get '/tweets' =>'posts#tweet', as: "tweet"

  post '/follow/:id' => 'relationships#follow', as: 'follow'
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord

  # スコープ（新着順）
  default_scope -> {order(created_at: :desc)}

  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: "Learner", foreign_key: "visiter_id", optional: true
  belongs_to :visited, class_name: "Learner", foreign_key: "visited_id", optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
  	# current_learnerの投稿に紐付いた通知一覧
  	@notifications = current_learner.passive_notifications
  	# notificationの中でまだ確認していない（indexに一度も遷移していない）通知のみ
  	@notifications.where(checked: false).each do |notification|
  		notification.update_attributes(checked: true)
  	end
  end

  def destroy_all
  	# 通知を全削除
  	@notifications = current_learner.passive_notifications.destroy_all
  	redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
  	@visiter = link_to notification.visiter.nickname, notification.visiter, style: "font-weight: bold; color: orange;"
  	@comment = nil
  	@your_post = link_to 'your post', notification.post, style: "font-weight: bold; color: orange;"
  	@visiter_comment = notification.comment_id
  	# notification.actionがfollowかfavoriteかcommentか
  	case notification.action
  	  when 'follow' then
  	  	"#{@visiter} " " followed you"
  	  when 'favorite' then
  	    "#{@visiter} good to #{@your_post}"
  	  when 'comment' then
  	  	@comment = Comment.find_by(id: notification.comment_id)&.comment
  	  	"#{@visiter} " " commented " " to #{@your_post}"
    end
  end

  def unchecked_notifications
  	@notifications = current_learner.passive_notifications.where(checked: false)
  end

end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% post = notification.post %>

<div class="learner-view clearfix ">
  <%= link_to learner_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg", size: "100x100", class:"profile-img-circle notification-image" %>
  <% end %>
  <span class="notification-type">
    <%== notification_form(notification) %>
  </span>
  <span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} ago)" %></span>

  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="font-size: 20px; color: white;"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="notifications-box">
<h3 class="text-center notification-index-title">Notifications</h3>
  <%= link_to destroy_all_path, method: :delete, class: "trash" do %>
    <i class="fas fa-trash" style="color: red;"></i>
    <h7 style="color: white;">delete_all</h7>
  <% end %>
  <hr>
  <% if @notifications.exists? %>
    <div class="learners-notification-index">
      <%= render @notifications %>
    </div>
  <% else %>
    <P class="no-notification">No notification</P>
  <% end %>
</div>