config/routes.rb
Rails.application.routes.draw do
  devise_for :learners

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  resources :learners, only: [:index, :show, :edit, :update] do
    get '/following' => 'relationships#following', as: 'following'
    get '/follower' => 'relationships#follower', as: 'follower'
  end

  resources :posts do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
  delete '/notifications/destroy_all' => 'notifications#destroy_all', as: 'destroy_all'


  get '/questions' => 'posts#question', as: "question"
  get '/tweets' =>'posts#tweet', as: "tweet"

  post '/follow/:id' => 'relationships#follow', as: 'follow'
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/learner.rb
class Learner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォロー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_learner, through: :follower, source: :followed
  has_many :follower_learner, through: :followed, source: :follower
  # //

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  # //

  attachment :profile_image

  validates :nickname, presence: true
  validates :country, presence: true
  validates :learning, presence: true
  validates :native, presence: true

  enum learning: { Japanese: 0, English: 1, Spanish: 2, German: 3, French: 4, Italian: 5 }
  # enum native: { japanese: 0, english: 1, spanish: 2, german: 3, french: 4, italian: 5 }

  def follow(learner_id)
    follower.create(followed_id: learner_id)
  end

  def unfollow(learner_id)
    follower.find_by(followed_id: learner_id).destroy
  end

  def following?(learner)
    following_learner.include?(learner)
  end


  def create_notification_follow!(current_learner)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ?", current_learner.id, id, "follow"])
    if temp.blank?
      notification = current_learner.active_notifications.new(
        visited_id: id,
        action: "follow"
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController

  before_action :authenticate_learner!, except: [:index]

  def index
  	@learners = Learner.all
  end

  def show
  	@learner = Learner.find(params[:id])
  end

  def edit
    @learner = Learner.find(params[:id])
    if @learner == current_learner
    else
      redirect_to learner_path(current_learner)
    end
  end

  def update
  	@learner = current_learner
  	if @learner.update(learner_params)
  	   redirect_to learner_path(@learner), notice: "Account information was updated!"
  	else
  	   render 'edit'
  	end
  end

  private

  def learner_params
  	params.require(:learner).permit(:nickname, :profile_image, :introduction, :country, :learning, :native)
  end


end

app/helpers/learners_helper.rb
module LearnersHelper
end

app/views/learners/edit.html.erb
<div class="learrner-edit">
  <div class="container">
    <div class="row">

      <div class="col-xs-10 col-xs-offset-1 learner-edit-form">

        <h2 class="learner-edit-title">edit profile</h2>

      <%= form_for(@learner) do |f| %>

      <!-- エラーメッセージ -->
        <div class="col-xs-12 error-box">
          <% if @learner.errors.any? %>
            <div class="error_explanation">
              <h3><%= @learner.errors.count %>error prohibited this obj from being saved:</h3>
              <ul class="error-color">
                <% @learner.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>

      <div class="row">

        <div class="col-xs-6 edit-left">

          <div class="edit-profile-image">
            <p class="edit-font">Profile Image</p>
            <%= attachment_image_tag @learner, :profile_image, :fill, 300, 150, fallback: "no_image.jpg", size: '300x200', onClick: "$('.profile-image-form').click()", class: "image img-responsive img_prev" %>
            <%= f.file_field :profile_image, class: "profile-image-form", style: "display: none;" %>
          </div>

        </div>

        <div class="col-xs-6 edit-right">

          <div class="edit-nickname">
            <p class="edit-font">Nickname</p>
            <%= f.text_field :nickname %>
          </div>

          <div class="edit-intro">
            <p class="edit-font">introduction</p>
            <%= f.text_area :introduction %>
          </div>

          <div class="edit-country">
            <p class="edit-font">country</p>
            <%= f.country_select :country, { include_blank: 'please select'}, class: "select-style" %>
          </div>

          <div class="edit-learning">
            <p class="edit-font">learning</p>
            <%= f.select :learning, Learner.learnings.keys.to_a %>
          </div>

          <div class="edit-native">
            <p class="edit-font">native</p>
            <%= f.select :native, { 'Japanese': 'Japanese' , 'English': 'English' , 'Spanish': 'Spanish' , 'German': 'German' , 'French': 'French' , 'Italian': 'Italian' } %>
          </div>



        </div>

        <div class="edit-update">
            <%= f.submit "Update", class: "btn btn-block btn-success" %>
          </div>

      </div>
      <% end %>

      </div>

    </div>
  </div>
</div>

app/views/learners/index.html.erb
<div class="container-fluid">
  <div class="row learner">
    <div class="col-lg-10 col-lg-offset-1">

      <h2 class="index-learners-title">Learners</h2>

      <table class="table learners-index">
        <thead>
          <tr>
            <th></th>
            <th>nickname</th>
            <th>country</th>
            <th>learning</th>
            <th>native</th>
            <th>followers</th>
          </tr>
        </thead>

        <tbody>
          <% @learners.each do |learner| %>
          <tr>
            <td><%= attachment_image_tag learner, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size: '80x80', class: "img-circle pull-left profile-thumb" %></td>
            <td>
              <%= link_to learner_path(learner), class: "nickname-decoration" do %>
                <%= learner.nickname %>
              <% end %>
            </td>
            <td><%= learner.country %></td>
            <td><%= learner.learning %></td>
            <td><%= learner.native %></td>
            <td><%= learner.followed.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/learners/show.html.erb
<section class="learner-info center-block">
  <div class="container-fluid">
    <div class="row">


      <div class="col-xs-12 learner-block">

        <% if flash[:notice] %>
          <p class="learner-update-success"><%= flash[:notice] %></p>
        <% end %>

        <!-- learner image/nickname -->
        <div class="learner-image">
          <%= attachment_image_tag @learner, :profile_image, :fill, 200, 200, fallback: "no_image.jpg", class: "img-circle" %>
          <p class="learner-nickname"><%= @learner.nickname %></p>
        </div>
        <!-- // -->

        <!-- country -->
        <div class="row country">
          <div class="col-xs-4 col-xs-offset-2">
            <p class="info-item">Country</p>
          </div>
          <div class="col-xs-2"></div>
          <div class="col-xs-3">
            <span><%= @learner.country %></span>
          </div>
        </div>
        <!-- // -->

        <!-- native -->
        <div class="row native">
          <div class="col-xs-4 col-xs-offset-2">
            <p class="info-item">Native</p>
          </div>
          <div class="col-xs-2"></div>
          <div class="col-xs-3">
            <span><%= @learner.native %></span>
          </div>
        </div>
        <!-- // -->

        <!-- learning -->
        <div class="row learning">
          <div class="col-xs-4 col-xs-offset-2">
            <p class="info-item">Learning</p>
          </div>
          <div class="col-xs-2"></div>
          <div class="col-xs-3">
            <span><%= @learner.learning %></span>
          </div>
        </div>
        <!-- // -->

        <!-- introduction -->
        <div class="row intro">
          <div class="col-xs-4 col-xs-offset-2">
            <p class="info-item">Introduction</p>
          </div>
          <div class="col-xs-2"></div>
          <div class="col-xs-3"></div>
        </div>

        <div class="row intro-detail">
          <div class="col-xs-10 col-xs-offset-2">
             <span><%= @learner.introduction %></span>
          </div>
        </div>
        <!-- // -->

        <div class="row link">

            <!-- 学習者編集/フォローボタン -->
            <div class="col-xs-4">
              <% if @learner.id == current_learner.id %>
                <%= link_to 'Edit', edit_learner_path(@learner), class: "btn btn-block btn-success" %>
              <% else %>
                <% if current_learner.following?(@learner) %>
                  <%= link_to 'unfollow', unfollow_path(@learner), method: :post, class: "btn btn-block btn-info" %>
                <% else %>
                  <%= link_to 'follow', follow_path(@learner), method: :post, class: "btn btn-block btn-danger" %>
                <% end %>
              <% end %>
            </div>

            <div class=col-xs-4>
              <%= link_to 'following', learner_following_path(@learner), class: "btn btn-block btn-primary" %>
            </div>
            <!-- // -->

            <!-- フォローボタン -->
            <div class="col-xs-4">
              <%= link_to 'follower', learner_follower_path(@learner), class: "btn btn-block btn-warning" %>
            </div>
            <!-- // -->

        </div>


        <!-- // -->


      </div>
    </div>
  </div>
</section>