config/routes.rb
Rails.application.routes.draw do
  devise_for :learners

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  resources :learners, only: [:index, :show, :edit, :update] do
    get '/following' => 'relationships#following', as: 'following'
    get '/follower' => 'relationships#follower', as: 'follower'
  end

  resources :posts do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
  delete '/notifications/destroy_all' => 'notifications#destroy_all', as: 'destroy_all'


  get '/questions' => 'posts#question', as: "question"
  get '/tweets' =>'posts#tweet', as: "tweet"

  post '/follow/:id' => 'relationships#follow', as: 'follow'
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :learner
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  attachment :image

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(learner)
  	favorites.where(learner_id: learner.id).exists?
  end

  def create_notification_by(current_learner)
  	notification = current_learner.active_notifications.new(
  	  post_id: id,
  	  visited_id: learner_id,
      action: "favorite"
  	)
  	notification.save if notification.valid?
  end

  def create_notification_comment!(current_learner, comment_id)
  	# 自分以外にコメントしている人を全て取得し、全員に通知を送る
  	temp_ids = Comment.select(:learner_id).where(post_id: id).where.not(learner_id: current_learner.id).distinct
  	temp_ids.each do |temp_id|
  		save_notification_comment!(current_learner, comment_id, temp_id['learner_id'])
  	end
  	# まだ誰もコメントしていない場合、投稿者に通知を送る
  	save_notification_comment!(current_learner, comment_id, learner_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_learner, comment_id, visited_id)
  	# コメントは複数回することが考えられるため、1つの投稿に複数回通知する
  	notification = current_learner.active_notifications.new(
  	  post_id: id,
  	  comment_id: comment_id,
  	  visited_id: visited_id,
  	  action: "comment"
	)
    # 自分の投稿に対するコメントの場合、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_learner!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.learner_id = current_learner.id
    if @post.save
       redirect_to posts_path, notice: "Posting was successful!"
    else
       render 'new'
    end
  end

  def index
  	@posts = Post.page(params[:page]).reverse_order
  end

  def question
    @posts = Post.where(genre: true)
  end

  def tweet
    @posts = Post.where(genre: false)
  end

  def show
  	@post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  	@post = Post.find(params[:id])
    if @post.learner == current_learner
    else
      redirect_to post_path(@post)
    end
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  	   redirect_to post_path, notice: "Post was updated!"
  	else
  	   render 'edit'
  	end
  end

  def destroy
  	@post =Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:image, :title, :body, :genre)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post-content">

  <% if post.genre == true %>
    <strong class="question-icon"><i class="far fa-question-circle"></i></strong>
  <% else %>
    <strong class="tweet-icon"><i class="far fa-smile-beam"></i></strong>
  <% end %>

  <!-- learner image/nickname -->
    <div class="learner-image-left">
      <%= attachment_image_tag post.learner, :profile_image, :fill, 60,60, fallback: "no_image.jpg", size: '80x80', class: "img-circle" %>
      <strong class="nickname">
        <%= link_to learner_path(post.learner.id) do %>
          <%= post.learner.nickname %>
        <% end %>
      </strong>
    </div>
  <!-- // -->

  <!-- post title -->
    <div class="post-title-center">
      <%= link_to post_path(post) do %>
        <%= post.title %>
      <% end %>
    </div>
  <!-- // -->

    <div class=" blank-space"></div>

  <!-- post body -->
    <div class="post-body">
      <%= post.body %>
    </div>

  <!-- post image -->
    <div class="post-index-image">
      <%= attachment_image_tag post, :image, :fill, 200, 150 %>
    </div>
  <!-- // -->

  <!-- コメント　アイコン -->
    <div class="post-footer">
      <strong class="comment-icon">
        <i class="far fa-comment"></i>
        <%= post.comments.count %>
      </strong>

    <!-- いいね　アイコン -->
      <strong class="good-icon">
        <% if post.favorited_by?(current_learner) %>
          <%= link_to post_favorites_path(post.id), method: :delete, remote: true do %>
            <i class="fas fa-heart red"></i>
          <% end %>
        <% else %>
          <%= link_to post_favorites_path(post.id), method: :post, remote: true do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
        <%= post.favorites.count %>
      </strong>
    </div>
  <!-- // -->


</div>

app/views/posts/_question.html.erb
<% posts.each do |post| %>
  <% if post.genre == true %>
    <div class="post-content-box <%= post.id %>", style="background-color: orange;">
  <% else %>
    <div class="post-content-box <%= post.id %>", style="background-color: blue;">
  <% end %>

      <%= render 'post', post: post %>

    </div>

<% end %>

app/views/posts/edit.html.erb
<section class="slice sct-color-1">
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 edit-form">

      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 edit-box">
          <div class="section-title-wrapper">
          	<h3 class="section-title">
          	  <span>Edit Post</span>
          	</h3>
          </div>

          <%= form_for(@post) do |f| %>

          <!-- エラーメッセージ -->
        <div class="col-xs-12 error-box">
          <% if @post.errors.any? %>
            <div class="error_explanation">
              <h3><%= @post.errors.count %>error prohibited this obj from being saved:</h3>
		      <ul class="error-color">
		        <% @post.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
		      </ul>
	        </div>
	        <% end %>
        </div>

          <!-- 画像登録フォーム -->
          <div class="row">
            <div class="col-xs-7">
              <div class="post-image">
                <%= f.attachment_field :image %>
              </div>
            </div>
          </div>
          <br>

          <!-- ジャンル選択フォーム -->
          <div class="row">
            <div class="col-xs-12">
              <div class="edit-post-genre">
                <%= f.radio_button :genre, :true, checked: true %>
                <%= f.label :genre, "question" %>
                <%= f.radio_button :genre, :false %>
                <%= f.label :genre, "tweet" %>
              </div>
            </div>
          </div>
          <!-- // -->


          <!-- タイトル入力フォーム -->
          <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
              <div class="edit-title-form">
                <%= f.text_field :title, class: "form-control", placeholder: "title" %>
              </div>
            </div>
          </div>
          <br>

          <!-- 本文入力フォーム -->
          <div class="row">
          	<div class="col-xs-12">
              <div class="edit-body">
                <%= f.text_area :body, class: "form-control", rows:"3", placeholder: "body" %>
              </div>
            </div>
          </div>
   		  <hr>

          <!-- 送信 -->
            <%= f.submit 'Update', class: "btn btn-block btn-success btn-base-1 mt-20" %>


          <% end %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<div class="container">

  <div class="row post-index">

    <% if flash[:notice] %>
      <p class="post-success"><%= flash[:notice] %></p>
    <% end %>

      <h2 class="index-main-title"><span class="question-color"><%= link_to 'Questions', question_path, class: "text-decoration-1", remote: true %></span>/<span class="tweet-color"><%= link_to 'Tweets', tweet_path, class: "text-decoration-2", remote: true %></span></h2>

      <!-- post index -->
      <div class="col-xs-12 post-index-right">

        <%= render 'question', posts: @posts %>

      </div>
      <!-- // -->

      <!-- pagination -->
      <div class="paginate">
        <%= paginate @posts %>
      </div>
      <!-- // -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/posts/new.html.erb
<section class="slice sct-color-1">
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 post-new-form">

      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 post-form">
          <div class="section-title-wrapper">
          	<h3 class="section-title">
          	  <span>New Post</span>
          	</h3>
          </div>

          <%= form_for(@post) do |f| %>

          <!-- エラーメッセージ -->
        <div class="col-xs-12 error-box">
          <% if @post.errors.any? %>
            <div class="error_explanation">
              <h3><%= @post.errors.count %>error prohibited this obj from being saved:</h3>
		          <ul class="error-color">
		            <% @post.errors.full_messages.each do |message| %>
			            <li><%= message %></li>
			          <% end %>
		          </ul>
	          </div>
	        <% end %>
        </div>


          <!-- 画像登録フォーム -->
          <div class="row">
            <div class="col-xs-7 col-xs-offset-2 post-image-box">
              <div class="post-image">
                <%= f.file_field :image, class: "img-field", style: "display: none;" %>
                <%= attachment_image_tag @post, :image, fallback: "no_image.jpg", size: "400x200", onClick: "$('.img-field').click()", class: "img-responsive" %>
              </div>
            </div>
          </div>
          <br>

          <!-- ジャンル選択フォーム -->
          <div class="row">
            <div class="col-xs-12">
              <div class="post-genre">
                <%= f.radio_button :genre, :true, checked: true %>
                <%= f.label :genre, "question" %>
                <%= f.radio_button :genre, :false %>
                <%= f.label :genre, "tweet" %>
              </div>
            </div>
          </div>
          <!-- // -->


          <!-- タイトル入力フォーム -->
          <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
              <div class="post-title">
                <%= f.text_field :title, class: "form-control", placeholder: "title" %>
              </div>
            </div>
          </div>
          <br>

          <!-- 本文入力フォーム -->
          <div class="row">
          	<div class="col-xs-12">
              <div class="post-body">
                <%= f.text_area :body, class: "form-control", rows:"3", placeholder: "body" %>
              </div>
            </div>
          </div>
   		  <hr>

          <!-- 送信 -->
            <%= f.submit 'submit', class: "btn btn-block btn-success btn-base-1 mt-20" %>


          <% end %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/question.js.erb
$(".post-index-right").html("<%= j(render 'question', posts: @posts) %>");

app/views/posts/show.html.erb
<div class="post-show">
  <div class="container-fluid post-show-content">

  <% if flash[:notice] %>
    <p clsss="post-update-success"><%= flash[:notice] %></p>
  <% end %>


    <!-- learner info -->
    <div class="wrapper">

      <div class="post-image">
        <%= attachment_image_tag @post, :image, :fill, 300, 300, fallback: "no_image.jpg", size: '300x300', class: "img-square" %>
      </div>

      <div class="profile-text">
        <div class="post-title", style="color: white;">
          <%= @post.title %>
        </div>
        <div class="post-body">
          <p class="body-text", style="color: white;">
            <%= @post.body %>
          </p>
        </div>
      </div>

    </div>
    <!-- // -->

    <!-- 編集/削除ボタン -->
    <% if @post.learner == current_learner %>
    <div class="links">
      <div class="edit-button">
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-block btn-success" %>
      </div>
      <div class="destroy-button">
        <%= link_to 'Destroy', post_path(@post), method: :delete, data: {confirm: "Are you sure？"}, class: "btn btn-block btn-danger" %>
      </div>
    </div>
    <% end %>

    <!-- // -->

    <!-- comment area -->
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">

        <table class="table comment-index">
          <thead>
            <tr>
              <th></th>
              <th class="comment-head">name</th>
              <th class="comment-head">comment</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody class="comment-area">

            <%= render 'comments/index', comments: @comments %>

          </tbody>
        </table>

        <!-- comment form -->
        <div class="row">
          <div class="col-xs-12">
            <%= form_with(model: [@post, @comment]) do |f| %>
              <%= f.text_area :comment, class: "form-control", rows:"3", placeholder: "comment here" %>
              <%= f.submit 'new comment', class: "btn btn-success btn-block center-block" %>
            <% end %>
          </div>
        </div>
        <!-- // -->

      </div>
    </div>
    <!-- // -->


  </div>
</div>

app/views/posts/tweet.js.erb
$(".post-index-right").html("<%= j(render 'question', posts: @posts) %>");