config/routes.rb
Rails.application.routes.draw do
  devise_for :learners

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  resources :learners, only: [:index, :show, :edit, :update] do
    get '/following' => 'relationships#following', as: 'following'
    get '/follower' => 'relationships#follower', as: 'follower'
  end

  resources :posts do
  resources :comments, only: [:create, :edit, :update, :destroy]
  resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]
  delete '/notifications/destroy_all' => 'notifications#destroy_all', as: 'destroy_all'


  get '/questions' => 'posts#question', as: "question"
  get '/tweets' =>'posts#tweet', as: "tweet"

  post '/follow/:id' => 'relationships#follow', as: 'follow'
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", style="background-color: rgba(0, 0, 0, 0.5);">


    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    <div class="header-logo">
      <%= link_to root_path do %>
        <h2 class="logo">HELLO WORLD</h2>
      <% end %>
    </div>

    </div>

    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <% if learner_signed_in? %>
          <li>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: gold;"></i>
            <% end %>
            <%= link_to 'Notice', notifications_path, class: "header-list-item"%>
          </li>
  	      <li><%= link_to 'My Page', learner_path(current_learner), class: "header-list-item" %></li>
  	      <li><%= link_to 'Post New', new_post_path, class: "header-list-item" %></li>
  	      <li><%= link_to 'Moments', posts_path, class: "header-list-item" %></li>
  	      <li><%= link_to 'Learners', learners_path, class: "header-list-item" %></li>
  	      <li><%= link_to 'Sign Out', destroy_learner_session_path, method: :delete, class: "header-list-item" %></li>
  	    <% else %>
          <li><%= link_to 'About', homes_about_path, class: "header-list-item" %></li>
          <li><%= link_to 'Learners', learners_path, class: "header-list-item" %></li>
          <li><%= link_to 'Sign Up', new_learner_registration_path, class: "header-list-item" %></li>
          <li><%= link_to 'Log In', new_learner_session_path, class: "header-list-item" %></li>
        <% end %>
      </ul>
    </nav>

  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/header' %>


  <main>
    <%= yield %>
  </main>

  <footer>
    <p class="footer-text">
      ©︎Hello World
    </p>
  </footer>

  </body>
</html>